FROM python:3.12-slim

WORKDIR /app
COPY script/ /app/script

WORKDIR /app/script
RUN python -m pip install --upgrade pip && \
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

ENV PYTHONUNBUFFERED=1

WORKDIR /app/script
ENTRYPOINT ["python", "formatter.py"]
